const data = {
  products: [
    {
      _id: '1',
      name: 'Nike slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'shirts',
      image: '/images/p1.jpg',
      price: 560,
      countInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '2',
      name: 'adidas fit shirt',
      slug: 'adidas-fit-shirt',
      category: 'shirts',
      image: '/images/p2.jpg',
      price: 590,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'nike Slim Pants',
      slug: 'nike-Slim-Pants',
      category: 'pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'adidas fit Pants',
      slug: 'Adidas-fit-Pants',
      category: 'pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};

export default data;
